version: '3'
services:
  node-app:
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    image: oeltoukhy/node-docker-app
  mongo:
      image: mongo
      restart: always
      volumes:
        - mongo-db:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
volumes:
  mongo-db: