version: '3'
services:
  node-app:
    container_name: compose-cont-dev
    build: 
      context: .
      target: development
    volumes:
      - ./src:/app/src:ro
    environment:
      - NODE_ENV=development
    command: npm run start-dev